{% set name = "zipstream-ng" %}
{% set version = "1.9.3" %}

package:
  name: zipstream-ng
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/z/zipstream_ng/zipstream_ng-{{ version }}.tar.gz
  sha256: 6cebd055025699c0af594c76a9452cdf13f4be67ee005b6907f0d3c9c6f44ced

build:
  entry_points:
    - zipserver=zipstream.server:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - zipstream
  commands:
    - pip check
    - zipserver --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pR0Ps/zipstream-ng
  summary: A modern and easy to use streamable zip file generator
  dev_url: https://github.com/pR0Ps/zipstream-ng
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
